# week08/.github/workflows/frontend-cd.yml

name: CD - Deploy Frontend to AKS (Reusable)

on:
  workflow_call:
    inputs:
      product_api_ip:
        required: true
        type: string
      order_api_ip:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      aks_resource_group:
        required: true
        type: string

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ inputs.aks_resource_group }}
          cluster-name: ${{ inputs.aks_cluster_name }}

      - name: Upsert frontend ConfigMap (runtime backend URLs)
        run: |
          kubectl create configmap frontend-config \
            --from-literal=PRODUCT_API_URL='${{ inputs.product_api_ip }}' \
            --from-literal=ORDER_API_URL='${{ inputs.order_api_ip }}' \
            -o yaml --dry-run=client | kubectl apply -f -

      - name: Deploy / Rollout frontend
        run: |
          cd k8s/
          kubectl apply -f frontend.yaml
          # kubectl rollout restart deploy/frontend
          kubectl rollout status deploy/frontend --timeout=180s

      - name: Logout
        if: always()
        run: az logout
