# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

# Triggers: manual, push, pull_request, repository_dispatch, and reusable workflow_call
on:
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types: [trigger-frontend-ci]
  pull_request:
    branches: [main, development]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  push:
    branches: [main, development]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

# Define global environment variables that can be used across jobs
env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
      - name: Logout from Azure
        run: az logout
        if: always()
